language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 http://localhost:80 # or some such

addons:
  - chrome # or google-chrome-stable

script:
    - ng build
    - ng test
    - ng e2e
