language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master
    
dist: trusty

addons:
  chrome: stable
  
before_script:
  - npm install -g @angular/cli
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
    - ng build
    - ng test
    - ng e2e
