language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  
addons:
   chrome: stable

script:
    - ng build
    - ng test
    - ng e2e
