language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master
    
sudo: required
addons:
  chrome: stable
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g @angular/cli

script:
    - ng build
    - ng test
    - ng e2e
